image: cirrusci/flutter

pipelines:
  pull-requests:
    feature/*:
      - step:
         caches:
          - gradle
          - gradlewrapper
          - flutter
         name: Run analyzer & test
         script:
          - cd beepforhelp
          - flutter pub get
          - flutter analyze
          - flutter test --coverage

    develop:
      - step:
         caches:
          - gradle
          - gradlewrapper
          - flutter
         name: Run analyzer & test
         script:
          - cd beepforhelp
          - flutter pub get
          - flutter analyze
          - flutter test --coverage

    hotfix/*:
      - step:
         caches:
          - gradle
          - gradlewrapper
          - flutter
         name: Run analyzer & test
         script:
          - cd beepforhelp
          - flutter pub get
          - flutter analyze
          - flutter test --coverage

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
    flutter: /opt/flutter